# this should run but not work as expected
def fail_at_runtime():
    myarr = [1,23,4]
    return True

fail_at_runtime()
