# this should run but not work as expected
def fail_at_runtime():
    print(8 == 4/2)

fail_at_runtime()
